### ISSUE TITLE
plugin crashes ember servers if there are linting issues

### ISSUE THREAD

**Issue by bcardarella** [DockYard/eslint-plugin-ember-suave#34] opened 2016-10-10 19:09 UTC
I may not be recalling correctly, but with suave I recall the linting errors still allowing the app and test servers to boot, they would just show warnings and would be output as failing tests.

Just now I imported a module, but had not used it yet. I started `ember test --server` and I saw the linting error but the server crashed.

```
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
TEST'EM 'SCRIPTS!
Open the URL below in a browser to connect.
http://localhost:7357/
━━━━━━━━━━━━━━┓
   PhantomJS  ┃     Chrome
    0/1 ◝     ┃   98/99 ✘
              ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━











Browser "phantomjs /Users/apple/work/web-experience-app/node_modules/testem/assets/phantom.js http://localhost:7357/6721/tests/index.html?hidepassed" exited unexpectedly with exit code null.
```

that being said, the Chrome tests still run, but Phantom is bombing out. Not sure if we should care about Phantom or if this would be considered an upstream issue.

**Comment by martndemus** [comment] 2016-10-10 19:11
If it is an issue, it's likely because it's an issue with ember-cli-eslint.

**Comment by Serabe** [comment] 2018-07-13 18:22
Closing as no longer reproducible. Thank you!

**Closed by Serabe** 2018-07-13 18:22 UTC
